#!/usr/bin/env bash
cd hydrator && go build; cd ..
mv hydrator/dev.env hydrator/.env
pnpm database:update && pnpm prepare:i18n && read -p 'Press Enter when messages/*.po are filled' && pnpm makeclean
mv hydrator/.env hydrator/dev.env
