#!/usr/bin/env bash
echo "ENVIRONMENT=prod" > hydrator/.env

pnpm database:update &&\
pnpm prepare:i18n &&\
pnpm makeclean &&\
cp dist/*.{png,xml,json,ico,css,js} dist/fr
mv dist/*.{png,xml,json,ico,css,js} dist/en
# TODO: use rclone sync instead to prevent copying uselessly identical files
rsync -r --progress dist/en/  ubuntu@ewen.works:/home/user-data/www/ewen.works/
rsync -r --progress dist/en/  ubuntu@ewen.works:/home/user-data/www/en.ewen.works/
rsync -r --progress dist/fr/  ubuntu@ewen.works:/home/user-data/www/fr.ewen.works/
rsync -r --progress assets/   ubuntu@ewen.works:/home/user-data/www/assets.ewen.works/
rsync -r --progress database/ ubuntu@ewen.works:/home/user-data/www/media.ewen.works/

echo "ENVIRONMENT=dev" > hydrator/.env
