extract colors:
  enabled: true

make thumbnails:
  enabled: true
  sizes: [100, 400, 600, 1200]
  file name template: <media directory>/<work id>/<media id>@<size>.webp

media:
  at: dist/media

build metadata file: database/.lastbuild.yaml
scattered mode folder: .portfoliodb/
