replace media sources:
  - replace: /mnt/datacore/projects/
    with: ''
  - replace: /home/ewen/projects/
    with: ''

extract colors:
  enabled: true

make thumbnails:
  enabled: true
  sizes: [400, 700, 1200]
  file name template: portfolio/media/<parent>/<media id>@<size>.webp

build metadata file: database/.lastbuild.yaml
